name: 每日稅務函釋爬蟲

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 安裝套件
      run: |
        pip install requests beautifulsoup4 pandas lxml python-dateutil
    
    - name: 執行爬蟲
      run: python tax_scraper_final.py
    
    - name: 上傳結果
      uses: actions/upload-artifact@v3
      with:
        name: tax-data
        path: data/
        retention-days: 30
'@ | Set-Clipboard

Write-Host "✅ 內容已複製到剪貼簿！" -ForegroundColor Green
