name: Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4 pandas lxml
      - run: python tax_scraper_final.py
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: data/
